site_name: "Chaosbahn"
site_url: https://chaosbahn.eu/
site_description: "Wir vernetzen Museumsbahnen und Nerds! Unser Ziel ist die Vereinfachung von Prozessen und Wissensaustausch unter Museumsbahnen."
repo_url: "https://github.com/museumsbahn-it-community/museumsbahn-knowledgebase"
edit_uri: "blob/main/docs/"

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    primary: blue grey

extra_css:
  - assets/style.css

plugins:
  - search
  - include_dir_to_nav

nav:
  - Einführung: "00 Einführung/Einführung"
  - Themenbereiche: "01 Themenbereiche"
  - "Decision Log": "04 Entscheidungsdokumentation (Decision Log)"
  - "Notizen": "99 Notizen"
  - "Mitmachen": "mitmachen.md"
  - "Impressum": "impressum.md"

